### ISSUE TITLE
PACKAGES: Implement mod-geo

### ISSUE THREAD

**Issue by winwisely111** [getcouragenow/packages#100]
implement flutter_map in the mod-geo

**Comment by winwisely99** [comment]
Upgrade to Android X to be clean.
Tracking: https://github.com/johnpryan/flutter_map/issues/533

**Comment by winwisely111** [comment]
Its already on android x

**Comment by winwisely111** [comment]
Next steps
- Have to implement markers ontap functionality
- add mod-geo to the maintemplate and see if its working fine

What else, not really e  now,
