### ISSUE TITLE
PACKAGES: mod-chat

### ISSUE THREAD

**Issue by winwisely104** [getcouragenow/packages#104]
Implement mod-chat for maintemplate

**Comment by winwisely99** [comment]
server folder:
  - IDIR then:
  - make sure nats using jetstream is setup locally with a make file for everyone dev !!
     - the cli should just use jetstream ( it has a untyped CLI structure that is superior ).

  - write a data pumper that CI can call to put fake data in.
    - the fake data is started from the CLI
    - make the cli be able to have an argument about if local or a domain. 
       - so then we can pump data into the cloud version OR the local version.

**Comment by winwisely99** [comment]
maintemplate/server:


maintemplate/server/main.go
- must import the various mod-* golang GRPC

mod-chat/server/main.go
- has a GRPC server


mod-write/server/main.go
- has a GRPC server

**Comment by winwisely112** [comment]
I deployed jetstream on k8s. I couldn't find any k8s manifest for it so wrote them by myself. they do not yet support clustering so I used persistent storage.

**Comment by WinWisely105** [comment]
I'm working on the frontend for this. @winwisely112 what's the status of the GRPC server? Should I prep to integrate it?

**Comment by winwisely112** [comment]
we can use this and import mods: https://github.com/grpc/grpc-go/tree/master/examples/features/multiplex

**Comment by Winwisly100** [comment]
currently the server on mod-chat use liftbridge as message queue we need to change I'm going to change it to jetstream.

**Comment by winwisely112** [comment]
I've written a simple chat server using jetstream. Client uses grpc to connect to server and server makes a subscription to related nats subject for them. They can broadcast a message using a grpc request and grpc server publishes it to nats. Other streams which are subscribed to the subject receive message from nats and send it to the clients.
The new client do not receive messages history. I added "DeliverAllAvailable" option for that as was mentioned in the docs but it had no effect. 
I changed the code and used nats streaming server. It worked with the same architecture and client was able to receive history.

**Comment by gedw99** [comment]
Thank you.

So this covers the base functionality required.

Need to add device ID. If need done in the frontend of mod-chat.
So you should be reviewing it to the backend.

**Comment by Winwisly100** [comment]
Now as we have a server using nats-streaming the CLI should be updated.

**Comment by winwisely99** [comment]
When the czlzi is updated let us know. Thanks.

It will be amazingly useful going forward be auss we can pump in different data for different customer demos 

Also smoke test data for our own internal regression testing on integration tests.

We will soon have to handle blobs with minio soon and so also then will gen images into minio and then the NATS tests data will have reference ID's to the blob / image data.
