### ISSUE TITLE
[PACKAGES] Release channels ( LOW priority, but work on if nothing else urgent)

### ISSUE THREAD

**Issue by winwisely112** [getcouragenow/packages#105]
- We need to use "Stable, Beta, Canary" channels now.
- Make a channel.json or yaml in the root of the repo where the githash of each channel has a value. 
   - e.g. "stable = 347375757, beta = fdhggdfgdfg, canary = dhdghdhfghdfh"
- CI will read the channel.json and then do the git checkout using that githash.
- we can then control whats used by just updating that channel.json in the master branch
- no need for tagging yet.

dNS:
maintemplate.stable.getcouragenow.org
maintemplate.beta.getcouragenow.org
maintemplate.ci.getcouragenow.org

this will allow UAT (User Acceptance people) people to test CI against a know githash.
then we can just tag code against that hash after that say its good.

**Comment by winwisely99** [comment]
This will need to dovetail with the flutter index.html cache busting hack !!
- at build time the githash can be added as a version
<script src="main.dart.js?version=2" type="application/javascript"></script>

**Comment by winwisely112** [comment]
For now, we can trigger stable release manually. git sha of stable release can be provided as a github secret. we can have just stable and CI channel. In an appropriate time I can develop a general solution and add other channels.

**Comment by winwisely99** [comment]
OK its thats the quickest.
