### ISSUE TITLE
PACKAGES: mod-ion

### ISSUE THREAD

**Issue by winwisely104** [getcouragenow/packages#107]
Create the mod-ion package

**Comment by winwisely99** [comment]
1. Master Page
 - list of other line ( does that now as you will see)
2. Detail page 
- actual video conf view

* If oyu can use the Master Detail responsive package that we use for mainTemplate even better as it will scale nicely for desktop and mobile

We dont need all the other stuff for demo, like data channel pags etc.

**Comment by winwisely104** [comment]
Master Detail with client list + call. Currently working only in same network. Master-Detail is a custom implementation since MasterDetailScaffold caused a deep problem with maintemplate.
