### ISSUE TITLE
PACKAGES: ION: Use Webview for Flutter Desktop

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#11]
Tracking ION issue here. https://github.com/pion/ion/issues/34

WebRTC and Video wil then work.

**Comment by joe-getcouragenow** [comment]
This is stalled for now

ASTI has a huge problem in that when bundled and installed, it then wants to unpack electron at runtime, which is nuts.

Zserge try is setup, but did not allow the camera / mic to work but need to have another do.
- its way way cleaner

**Comment by joe-getcouragenow** [comment]
Update

@cloudwebrtc tested the zerge approahc and Apples WebView does NOT allow WebRTC
Don't you love Apple and its policy of crippling IOS and MAC so its hard as possible to run Webrtc, so that you are forced to use FaceTime

**Comment by winwisely99** [comment]
Update

So the easy way to get this done and to have a reusable webview that works with webrtc is to simply run ASTI and collect the Framework files it produces at runtime.

Then embed those framework files into the hover build 

The standard Asti golang code should still work because it is expecting the framework files to be there anyway !

It might require some small changes to the Asti code in terms of patching.it will I expect some small changes to hover packaging so that the electron framework files are also included in the packaging.

Also it's vital that when a webview window is opened the OS taskbar does not show it as another app. At the moment it does with ASTI but does not with zserge. I imaging this might mean some small changes to Asti code of our golang webview code.

This will get us a nice reusable webview that can be used for video conf, watching videos and oAth sign in among other tjing that we know we need this for.

If you need to fork Asti or other code please let me know so we can first do the fork in this get courage repo first so that it stays here

**Comment by joe-getcouragenow** [comment]
I opened an Issue over at Zserge to ask if its possible or not:
https://github.com/zserge/webview/issues/368

It would be awesome if it is !!
