### ISSUE TITLE
PACKAGES: main-template pwa text and icons is wrong

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#120]
@winwisely111

https://maintemplate.ci.getcouragenow.org/#/

- still not using the logo
- icon not working
- change text that appears. 

---

android 27 SDK
chrome browser

stage 1
![photo_2020-03-03 18 13 14](https://user-images.githubusercontent.com/56028033/75800964-a989e000-5d7a-11ea-96b9-9a68b4a647ea.jpeg)

stage 2
![photo_2020-03-03 18 10 31](https://user-images.githubusercontent.com/56028033/75800720-4dbf5700-5d7a-11ea-99fc-2be20bca4954.jpeg)

stage 3
![photo_2020-03-03 18 06 58](https://user-images.githubusercontent.com/56028033/75800416-ce318800-5d79-11ea-93d3-95ca0bac3ca8.jpeg)

stage 4
![photo_2020-03-03 18 09 22](https://user-images.githubusercontent.com/56028033/75800606-2072a900-5d7a-11ea-8fc4-30d4e1334307.jpeg)

---

ios  ?

**Comment by winwisely99** [comment]
iOS

![IMG_20200303_194304_951](https://user-images.githubusercontent.com/56028033/75808403-55d1c380-5d87-11ea-8d8a-75c92a19f894.jpg)


![IMG_20200303_194311_075](https://user-images.githubusercontent.com/56028033/75808437-62eeb280-5d87-11ea-8dc4-0c1713fd66d1.jpg)


![IMG_20200303_194314_041](https://user-images.githubusercontent.com/56028033/75808459-6da94780-5d87-11ea-987c-eede35bb9f96.jpg)

**Comment by winwisely111** [comment]
Text changed to ```GetCourage```
Icons chnaged to ```Your Logo Here.png```
