### ISSUE TITLE
PACKAGE: mod-chat : messages response not reliable

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#124]
needed to say hello twice before it responds

![Screenshot 2020-03-03 at 18 47 54](https://user-images.githubusercontent.com/56028033/75803977-9af1f780-5d7f-11ea-9860-3686cfcce6fc.png)

**Comment by winwisely112** [comment]
It is not a grpc-web issue. The server is very simple and only for test. It delivers the message just to one of subscribed clients. Perhaps you have subscribed twice using another browser window.

**Comment by gedw99** [comment]
Ok understand.
No worries. That's next stage

**Comment by winwisely99** [comment]
@ali_djavadi just before I pass out. You will need a flutter package for mod-chat that gets the device UUID / ID. So then you know the exact device the chat message came from and can route it through on the backend correctly back up to the front of. It's basically a session ID like normal web requests.



Get a flutter Dev to add it. Your protobuf needs to pass it. Or maybe headers - Depends I think on envoy.

**Comment by winwisely99** [comment]
Needs to work on web, desktop and mobile.

Not sure how a device ID is fingerprinted on web.

https://pub.dev/packages/device_id
- looking at issues seems broken

https://stackoverflow.com/questions/45031499/how-to-get-unique-device-id-in-flutter
- site but no web support.


Or maybe we need a user logged in and use traditional session approach actually.
That is probably the first step !!!

**Comment by winwisely104** [comment]
We could do it like webrtc, for any OS:
`Platform.localHostname + '(' + Platform.operatingSystem + ")";`
for web
`'Flutter Web ( ' + HTML.window.navigator.userAgent + ' )';`
Is this reliable? I guess there are duplicated userAgents out there?
Or we can create a token and save it locally, like a session.

**Comment by winwisely104** [comment]
Didn't merge it yet, but the code is on my fork:
https://github.com/winwisely104/packages/commit/41743fa8d7a87ef84f21b07b5ab9e165274b78f2
To receive the device info as possible UID. In the commit you can also see how to do the import. Use label for the uid.
