### ISSUE TITLE
Packages: version of githash and Device ID in Settings GUI

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#136]
We are recording the githash for the cache buster issue.

We should write to an asset file in maintemplate to override what is there.

Leonard can quickly add a Version name and value to the Setting screen
- just have the value driven from an asset.json 

Ali just needs to put the githash into that assets/version.json file before the CI build occurs just like what he does for the cache buster.

**Comment by winwisely104** [comment]
The file is called "env.json" and located in maintemplate/client/assets/env.json.
The values are shown in the Settingsview.

`{
	"channel": "#{channel_name}",
        "url": "#{channel_url}",
	"githash": "#{channel_githash}"
}`

**Comment by winwisely104** [comment]
add key value: 'flutter_channel'
