### ISSUE TITLE
PACKAGE: mod-ion: Make Server URL discoverable.

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#142]
https://github.com/getcouragenow/packages/blob/master/mod-ion/client/lib/ion_module.dart#L35

At the moment its hard coded.

THIS APPLIES TO ALL OUR SERVICE and not just ION 

We need the URL to be easily changable to allow us to run ION
- local
- cloud

SO the frontend code needs to ask something "give me the ion server for ci" and "give me the ion server for beta", etc.
The front end code needs a setting ( probably in assets) that say "env=ci" or "env=beta", etc

---

Service Discovery pattern.
We could use the DNS for public Service Discovery ?

**Comment by winwisely104** [comment]
We could do it through environment variables, but then we need a pre build script running. Or we do it simply with different main.dart files. E.g. dev_main.dart, prod_main.dart.  These files have the properties set and start the applications.
