### ISSUE TITLE
PACKAGE: BUILD breaking due to route API error

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#143]
https://github.com/flutter/flutter/issues/45938

Issue inside flutter: https://github.com/flutter/flutter/issues/45938#issuecomment-591663253

solution is to move our local and ci to beta channel for now.

then leonard you can write the Modular Flutter guys with an issue please ??

**Comment by winwisely104** [comment]
There is already an issue
https://github.com/Flutterando/modular/issues/63

**Comment by winwisely104** [comment]
switchet back to beta for now https://github.com/getcouragenow/packages/commit/2a91fcba6a7e775569a6b3c56da2fb51e47ef94d

**Comment by winwisely104** [comment]
https://github.com/getcouragenow/packages/pull/166
