### ISSUE TITLE
PACKAGES: anonymous Metrics

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#148]
Aggregate anonymous Metrics.

Facets:
Number of campaigns
Users 
Users per campaign
Usage of collaboration tools

---

Real time
Over time

---

Security
Would be good for campaign is era to be able to see their data
Then global for campaign of campaign owners 

----

GUI

Would be nice to have a flutter based view on it

---

Reports

Would be nice to have reporting at different levels

**Comment by valyala** [comment]
This sounds like an analytics project. Take a look at https://clickhouse.tech/ . It could be better suited to such a project than VictoriaMetrics.

**Comment by winwisely99** [comment]
@valyala thank you . Will have a look !!

**Comment by valyala** [comment]
VictoriaMetrics could be good fit for this project. Note that it accepts only time series with `(timestamp, value)` pairs, where `value` is float64 number. It doesn't work well with arbitrary string values unlike ClickHouse. See https://medium.com/@valyala/prometheus-storage-technical-terms-for-humans-4ab4de6c3d48 for details.

**Comment by winwisely99** [comment]
@valyala thanks for helping..

TimeSeries seems perfect for our analytics 
- because for each org we have maybe 5 to 10 biz metrics to track over time
- and then make its pretty PDF chats. 
- The org biz metrics are all float64, so VictoriaMetrics looks like a good fit.

Because of the virus we are in a big rush to roll this out to gov and eu departments
- online video with chat and docs is what they need. 
- They use signal inside EU also but its not useful for this.

So if you know of an example golang project that does the above let us know.
I am also searching.

**Comment by winwisely99** [comment]
Easy to sue from our golang microservices
https://github.com/VictoriaMetrics/metrics#usage

Easy to install using helm
https://github.com/VictoriaMetrics/helm-charts

**Comment by winwisely99** [comment]
@winwisely112 
For minio, nats and Victoria Metric we can use HELM against the current k8 setup ?
Instead of the way we do it now where we hand code the dockers.
