### ISSUE TITLE
Flutter file and .gitignore

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#151]
...For some reason i had trouble stopping the .flutter-plugins-dependencies being checked in for all: https://github.com/getcouragenow/packages/pull/150/files#diff-ff0d90454de7682370acad84eb241a8eR74

Maybe you know the secret .gitignore syntax ??

Its will kick us hard if this is not fixed...

@winwisely112 can you fix it as i am sure you know that .gitignore syntax i am missing

Its in all the packages folders maybe...

**Comment by winwisely112** [comment]
I think this is not a ```.gitignore``` syntax issue. have you tried ```git rm --cached```?
