### ISSUE TITLE
PACKAGES: mod-template settings overflows on Desktop

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#197]
FYI: @winwisely111 

![Screenshot 2020-03-10 at 13 41 27](https://user-images.githubusercontent.com/56028033/76313283-ef8ff800-62d4-11ea-8809-b946a4f602a0.png)

Context:
- mac

REPRO:
- Settings > change language.
- will cause the overflow error as seen in the screenshot

**Comment by winwisely111** [comment]
couldn't reproduce this bug on beta channel on windows

**Comment by winwisely99** [comment]
closing. Might be becaue i was on dev channel.
hence we we will wont to do CI with different flutter channels later.
