### ISSUE TITLE
PACKAGES: mod-main bugs

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#213]
FYI: @winwisely111 

1. does not run on desktop

![Screenshot 2020-03-11 at 08 27 18](https://user-images.githubusercontent.com/56028033/76392814-9d9daf80-6372-11ea-8daf-a5c97cfa0747.png)

2. DONT COPY exactly ! Make it the same style / structure as maintemplate.

- My Campaign on left not needed (It already says "Search Campaigns" in the title bar)
- "NY STATE pipelne ..: " titel on the right should be in the title bar.

![Screenshot 2020-03-11 at 08 30 57](https://user-images.githubusercontent.com/56028033/76392848-ae4e2580-6372-11ea-8635-3871e1523ec1.png)

3 Code names

````
*** Modular Routers ***

/                    => SplashView
/userInfo/userInfo   => UserInfoView
/campaigns/campaigns => CampaignView

*****

-- AppModule INITIALIZED
-- SplashModule INITIALIZED
-- UserInfoModule INITIALIZED
-- SplashModule DISPOSED
-- CampaignModule INITIALIZED
````
- "campaigns" should be "orgs". We want to think flat hierarchy.
- Splash not needed ( will be from maintemplate)

**Comment by winwisely111** [comment]
* no im not copying it exactly, the architecture is totally different as in the maintemplate
* just using the views from main repo, rest all is being well structured like main template

* okiee i will remove splash, i used the splash with the the thought that this route can be imported into main template as the first route and all can be handles in the mod-main.
