### ISSUE TITLE
PACKAGES: ensure mod-chat has one connection in a singleton

### ISSUE THREAD

**Issue by winwisely104** [getcouragenow/packages#219]
Right now mod_chat opens a connection on every tap on the chat icon, which leads to start a new isolate every time. 

The connection should be decoupled to the ui, so we have a singleton for the connection and every new instance of mod_chat uses this single connection.

**Comment by winwisely104** [comment]
The first time you go to chat within the maintemplate the service is establishing a connection to the server. The connection is a singleton and stays alive as long as the app is started.

**Comment by joe-getcouragenow** [comment]
Can you test on Desktop, android and Web and make sure it IS singleton.
Just want to make sure before we get the other modules to use this pattern.

**Comment by winwisely104** [comment]
Confirmed on Desktop, android and web!
