### ISSUE TITLE
PACKAGE: mod-settings - Theme and Night Mode split

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#239]
0. Get Night mode detected on Desktop
- See main rpeo as we got it working there.

1. The Word "Theme" in the Settings page to be changed to be called "Auto Night mode"

![Screenshot 2020-03-12 at 15 58 17](https://user-images.githubusercontent.com/56028033/76534829-500c6a00-647a-11ea-9919-a59f117e72e0.png)

![Screenshot 2020-03-12 at 15 59 37](https://user-images.githubusercontent.com/56028033/76535005-81853580-647a-11ea-980e-e051342f441e.png)

2. Theme Support

![Screenshot 2020-03-12 at 16 00 18](https://user-images.githubusercontent.com/56028033/76535066-9661c900-647a-11ea-9fd8-4cb201655014.png)

- Make 2 BASIC themes. These are just to test the architecture.
   -there is package on dart pub that manages this i think.
- make the setting simialr to above.

**Comment by winwisely111** [comment]
@winwisely99 Two basic themes, and by that u mean dark and light, or other than that?
