### ISSUE TITLE
PACKAGE: Get i18n working in mainTemplate

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#24]
golang and flutter tools tools up and working.

Intent: 
SO that devs that use a package have all the i18n already done in the package.
SO the ARBS and darts are all checked in.

Where:
DO Here:https://github.com/getcouragenow/bootstrap/tree/master/tool
- rename i18n
- dev needs to pull the repo and compile into gobin.
- then dev uses it from his makefile.

Example:
https://github.com/go-flutter-desktop/examples/tree/master/stocks/lib/i18n

FLOW
1. Gen the ARBs file from the https://github.com/go-flutter-desktop/examples/blob/master/stocks/lib/stock_strings.dart

2. Gen the ARB specific to each lang.

3. Parse the intl_messages.arb to get the global English terms.

4. Parse the lang specific ARB's, and gen OUR translated lang specific JSON ( machine and human)
- golang code that under the hood called google translate. No need for google sheets.
- JSONS allow human overrides. 
- SEE: https://github.com/getcouragenow/network/tree/master/translate

5. lang specific JSON --> back into the lang specific ARB

8. ARB's --> DART's (stock_messages_<locale>.dart)

---

LATER:
- can apply this to all our modules in packages like cal, write.

**Comment by Winwisly100** [comment]
I finished the tool and we should test it with flutter
