### ISSUE TITLE
PACKAGE: mod-settings needs a littel bit of extensibility

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#240]
CURRENT:
![Screenshot 2020-03-12 at 16 05 46](https://user-images.githubusercontent.com/56028033/76535566-60711480-647b-11ea-8cfa-817940fc7e63.png)

---

NEW:
![Screenshot 2020-03-12 at 16 02 16](https://user-images.githubusercontent.com/56028033/76535273-e93b8080-647a-11ea-94c9-3391eb5e4ae6.png)

We dont have enough space for the settings now when its all on the one page.
- use the same Telegram approach
   - scaffold the same left menu
   - scaffold the pages for each page

TEST TEST on each device and device size BEFORE doing anything else.

then add the Lang, Theme and NIGHT mode as per:

**Comment by winwisely111** [comment]
@winwisely99 Settings space is scrollable, so we can keep adding and it will be scroll able view,,
