### ISSUE TITLE
PACKAGES: data table action icons having many issues

### ISSUE THREAD

**Issue by winwisely111** [getcouragenow/packages#294]
Datatable for the mobile view shows scrollable list of data, and displays action icon buttons, below the list. 

The following does not work:

1. Check box toggle for ALL items working.
2. Check box toggle for SINGLE items not working.
3. Hamburger not appearing once you have used it once.

Why it does not work ?

The issue is caused by the Responsive package we use.
The change notifier only rebuilds the master page, not details page because it was pushed on top

Decision:
The group decision is to wait on Google's Navigator 2.0 and see if maybe it makes this architectural issue easier to resolve. Right now we are just doing hacks that fix it for Mobile and then break the GUI for Desktop.

Rody's:
Code:https://github.com/rodydavis/data_tables/tree/master/example/lib
Demo: https://rodydavis.github.io/data_tables/#/

Ours:
Code: https://github.com/getcouragenow/packages/tree/master/mod-main/client/lib/modules/org_manager/orgs
Demo: https://maintemplate.ci.getcouragenow.org/#/enrollement/dashboard

![Screenshot_20200326-185948](https://user-images.githubusercontent.com/60743306/77656129-38aea000-6f95-11ea-962b-d0ac202560fb.jpg)

**Comment by winwisely99** [comment]
This might be a viable option for this problem:

https://github.com/Flutterando/modular/blob/master/README.md#routeroutlet

As it does Ribes it allows a module to interoperate with the navigator / router that Modular controls

**Comment by winwisely111** [comment]
Implemented Router Outlet

Findings
- it needs us to give each tab an initial route which is essentially "/" or initial route of the application.
- Flutter modular doesn't binds the sub routes like tab1/page1 , that means if we copy paste the url application will be redirected to the initial route, it cant find particular route(tab1/page1) because it wasnt bound like other routes. and it kills our purpose.


Flutter has released a new navigation rail widget on master channel. That can be given a try, may be it solves our issue . May be it is implemented with navigator 2.0 (Not sure, just guessing).
