### ISSUE TITLE
PACKAGE: maintemplate layout

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#297]
FYI: @winwisely111 
https://maintemplate.ci.getcouragenow.org/#/enrollement/dashboard

![Screenshot 2020-03-26 at 19 34 07](https://user-images.githubusercontent.com/59567750/77683821-4a924200-6f99-11ea-86f0-a1bbbdd59ad0.png)

Can we make these shorter. See Green lines...
Its too wide and wasting space. 
Let me know if you need to customise existing dependency.
Please test on IPAD and Desktop in the Web Browser

**Comment by winwisely111** [comment]
Yes it can be made shorter and yes it needs customization of dependency (responsive scaffold)

**Comment by winwisely99** [comment]
Let's leave it for now.
Gotta sort out the navigation bug first
