### ISSUE TITLE
Maintemplate : pass events between pages

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#304]
With a modular Architecture each module is not aware of the other.
.a common pattern to solve this is to use an event bus that all modules use to pass typed or untyped messages of data to each other.

https://github.com/OpenFlutter/Flutter-Notebook/tree/master/mecury_project/example/event_bus_demo

This should reside in maintemplate to allow all modules to have access to the bus.

Each module can implement pub and sub functions as strongly typed data signatures.

Maintemplate can then route the messages between them performing any message transformation required.

---

There is likely to be use cases of standard messages that all modules need. These can be in package called events.

**Comment by joe-getcouragenow** [comment]
Main entry point is here:
https://github.com/getcouragenow/packages/tree/master/maintemplate/client

Point at which event bus would fix things

From https://maintemplate.ci.getcouragenow.org/#/enrollement/orgs, READY button goes to Sign In page

From https://maintemplate.ci.getcouragenow.org/#/enrollement/myneeds/orgs/1, Next and NO, goes to Sign page in Signin module

From https://maintemplate.ci.getcouragenow.org/#/enrollement/supportRoles/orgs/1, Next goes to SignIn page, in Sign In Module

**Comment by joe-getcouragenow** [comment]
Signin:
https://github.com/getcouragenow/packages/tree/master/maintemplate/client/lib/modules/login

Its just a stub page for now.

**Comment by json469** [comment]
Time boxing 2 hours on this one GLHF 👍

**Comment by joe-getcouragenow** [comment]
good luck !!
when you make PR; please add the Issue number
