### ISSUE TITLE
Rail package does not update when back pushed

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#308]
Looks like why we can control our nav properly.

Tracking :https://github.com/Flutterando/modular/issues/82

**Comment by winwisely99** [comment]
@winwisely111

**Comment by joe-getcouragenow** [comment]
Reproduction:

1. go here: https://maintemplate.ci.getcouragenow.org/#/geo
2. Click the "Writer Icon"
3. Click the back button.
- It does NOT go back to Maps

**Comment by winwisely111** [comment]
- It does go back to maps but the icon doesn't gets updated, its not the flutter modular issue, rather its bcz of navigation rails

This issue explains this https://github.com/getcouragenow/packages/issues/312

**Comment by winwisely99** [comment]
Closing as another issues covers this
