### ISSUE TITLE
PACKAGING: desktop bugs

### ISSUE THREAD

**Issue by Winwisly100** [getcouragenow/packages#315]
Some issues with desktop app:

**Macos-pkg:**
1. There is no desktop icon.

![2020-04-06 20 10 22](https://user-images.githubusercontent.com/56028033/78590788-a9ca3f00-7842-11ea-9f4e-d420a31fa6fd.jpg)

---

2. resize bug.

![2020-04-06 20 10 01](https://user-images.githubusercontent.com/56028033/78590767-9e771380-7842-11ea-89a1-84866bc94435.jpg)

---

**Comment by winwisely99** [comment]
![2020-04-06 20 10 01](https://user-images.githubusercontent.com/56028033/78590767-9e771380-7842-11ea-89a1-84866bc94435.jpg)


![2020-04-06 20 10 22](https://user-images.githubusercontent.com/56028033/78590788-a9ca3f00-7842-11ea-9f4e-d420a31fa6fd.jpg)


![2020-04-06 20 10 43](https://user-images.githubusercontent.com/56028033/78590815-b8b0f180-7842-11ea-9a17-8e87fa169ebb.jpg)

**Comment by winwisely111** [comment]
### Win-pkg:

    1. Installer terminates after this
![Screenshot (6)](https://user-images.githubusercontent.com/60743306/78639554-9a410980-78c7-11ea-8526-a95a28bfb4f1.png)
