### ISSUE TITLE
PACKAGES: Mod-chat grpc native needs the config setting and adjustments

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#332]
The env.json holds the config settings.
the flutter code picks it up.

See here: https://maintemplate.ci.getcouragenow.org/#/settings

Mod-chat uses those config values:
https://maintemplate.ci.getcouragenow.org/#/chat

At the moment mod.chat grpc-web works, but the config setting have not been exposed to the GRPC, so that Desktop and Mobile GRPC works.

--

Env:
Url: maintemplate.ci.getcouragenow.org
UrlNative: grpc.maintemplate.ci.getcouragenow.org

The env.json has these values hardcoded for you so you can run locally. !!

--

The code:

The web grpc server is given the config settings and so works:
https://github.com/getcouragenow/packages/blob/master/mod-chat/client/lib/grpc_web_example/api/chat_service_web.dart

The native grpc needs to be given the config settings though:
https://github.com/getcouragenow/packages/blob/master/mod-chat/client/lib/grpc_web_example/api/chat_service.dart

**Comment by joe-getcouragenow** [comment]
assigned to @ArchitectNate
ongoing...

PLEASE quote the Issue number on PR's
