### ISSUE TITLE
PACKAGES: mod-ion backend and frontend

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#350]
ion docker compose is setting there in our repo as a make file, to allow us to start to integrate it.

its here: https://github.com/getcouragenow/packages/tree/master/mod-ion/server

It has new functionality to allow multi party vid conferencing.

frontend:
- adjust frontend dart as required.
- check that the path to the server is a config setting, and then integrate the Config protobuf to drive it

Backend:

FYI: @cloudwebrtc 
- Hosting
   - For now just getting this running as a docker compose is fine so we can get the module running locally
   - We need to figure out how to host it in k8 as a docker compose OR do what Liftbridge does. I like how liftbridge does it actually in that it support docker compose and k8 with skaffold
  - https://github.com/liftbridge-io/liftbridge
  - https://github.com/liftbridge-io/liftbridge/tree/master/docker
  - https://github.com/liftbridge-io/liftbridge/tree/master/k8s

FYI: @cloudwebrtc 
- Getting our users and user security integrated
  - We use Envoy as a standard way of enforcing Security.
  - It can run in docker compose and k8, and so ion team can also use it.
  - Its a good approach because its languages agnostic allowing
  - Ion code will need to be changed to support it.

FYI: @cloudwebrtc 
- GRPC and GRPC-web
   - We use envoy to do all the GRPC and GRPC-Web stuff automatically for us
   - Its a standard and you can codegen the Frontend and Backend code from the protobufs and Envoy does all the works at runtime of making everything work. 
  - Ion team could use it and then their JS and Dart code is reduced and faster

FYI: @cloudwebrtc 
- Getting it using TIDB CDC with NATS / Liftbridge
  - This will mean that the RediS API stays but there is a flag for their code to use TIDB CDC
  - Because Ion is sync, it wont need NATS. Instead it will get the Event of the data structure change and send to the Ion code, which then takes over reacting to it.

**Comment by winwisely104** [comment]
Can't make the actual ion flutter example work. Blocked for now.
Issue here: 
https://github.com/pion/ion-sdk-flutter/issues/3
