### ISSUE TITLE
PACKAGES: Use env.json to manage language options in settings

### ISSUE THREAD

**Issue by ArchitectNate** [getcouragenow/packages#360]
Use env.json to manage language options in settings:

Example Schema:
```
{
     // ...

     "locales": ["system", "en", "es", "fr", "ur"]

    // ...
}
```

The code should default to it's current functionality if no locales key exists or if it's empty.

**Comment by winwisely199** [comment]
This is done

**Comment by winwisely199** [comment]
Completed via the following PRs:
https://github.com/getcouragenow/packages/pull/363
https://github.com/getcouragenow/packages/pull/365
