### ISSUE TITLE
PACKAGES: Settings. Use env.json to control what Languages are shown in drop down not working

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#364]
Settings - env.json to only show EN. 

Currently it is not enforcing it in the Setting GUI...I see 4 languages still: https://maintemplate.ci.getcouragenow.org/#/settings

**Comment by joe-getcouragenow** [comment]
@winwisely199 
Assign your self please.

**Comment by winwisely199** [comment]
> @winwisely199
> Assign your self please.

I don't seem to have permissions to do so

**Comment by winwisely199** [comment]
@joe-getcouragenow The issue is that I need to update env-template.json

I can hardcode the locale in there for now, or we can create an environment variable to be set during the build process.

**Comment by winwisely199** [comment]
Completed with: 
https://github.com/getcouragenow/packages/pull/366
https://github.com/getcouragenow/packages/pull/365
