### ISSUE TITLE
PACKAGES: mod-main Makefile initial creation

### ISSUE THREAD

**Issue by winwisely199** [getcouragenow/packages#368]
Need to create the Makefile with the basic go run commands for mod-main

**Comment by joe-getcouragenow** [comment]
1. suck down the data from gsheets into data folder
- add not to install bootstrap, and show it working in make file
- add config for the gsheets ( example in bootstrap)
- setup gsheets CSV export on google drive and add them to config.
2. wire up golang client to use them
- Just at least get them fmt-printing for now.
- pass to grpc server. Dont have yet.

**Comment by winwisely199** [comment]
> * add not to install bootstrap, and show it working in make file

You mean that the Makefile should be able to do it without the bootstrap installation?

**Comment by winwisely199** [comment]
Done
