### ISSUE TITLE
PACKAGES: mod-geo country drill down

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#395]
https://github.com/imtoori/CountryCodePicker/blob/master/README.md

Simple country picker

It also shows the i18n bottom up approach for packages . Looks simple.

**Comment by winwisely111** [comment]
Country picker needs to be implemented in a separated module - mod-timespace

**Comment by winwisely99** [comment]
https://github.com/miguelpruivo/country_codes

This is hardcoded and useful as we need this.
We still need a database of the data also as it will be needed for so many dackend operations.
So maybe the data in this can be codegenerated from the data in the first item of the issues
