### ISSUE TITLE
PACKAGE: CI - ci-env regression failure with HELM

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#405]
About every 2 or 3 weeks, we get a CI failure when we try to deploy to k8.

Here is an historical one:
https://github.com/getcouragenow/packages/runs/595650529?check_suite_focus=true

The quick fix is to delete the Services:
```
kubectl delete svc ci-flutter
kubectl delete svc ci-envoy
kubectl delete svc ci-maintemplate
````
And then rerun CI

---

Also during this even i noticed that when i upgraded k8, the nodes had to be manually upgraded afterwards. This shoudl be changed for the nodes to autoupgrade allow with the k8 Cluster i presume ?

---

But this wont do for Production :)

Please suggest fixes...

**Comment by WinWisely268** [comment]
https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-upgrades 

should fix the node auto upgrade problem. 


The problem with the helm issue is it is completely random, and it won't kick off rebuild once the initial deployment is failed, maybe we need to use helm 3 --atomic option?

**Comment by joe-getcouragenow** [comment]
Should try it on k8 DEV ENV first ?

**Comment by WinWisely268** [comment]
yep, exactly
