### ISSUE TITLE
PACKAGES: Printing - research

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#410]
Dashboard will need to produce pdf reports

The user will make them on the spot.
The backend will send them occasionally via email job.

https://pub.dev/packages/pdf

This can produce a pdf using da
It can print on mobile. Not sure about web printing but we will need it for web and ASTI desktop.

Server side we can use dart to produce the same dart to make pdf. Running this as. Service from golang calling into dart might be possible. Dart can compile as AOT these days and so it's plausible that at runtime we won't see dart which I would really prefer.

**Comment by winwisely99** [comment]
The plugins repo has it.

We need to do it there first Nd get it working for desktop
The easiest way is I think to use the webview plugin because it will use the electron print and print preview native GUI and OS print drivers !! That remove a ton of extra work.

I just don't know if ASTI golang has an API to the Electron print API.
If it does not it's simpler to extend ASTI thN it is to write your own printing codd

**Comment by winwisely99** [comment]
https://github.com/asticode/astilectron/issues/25

**Comment by joe-getcouragenow** [comment]
it's an idea to add a button to full screen the details view for printing.

![Screenshot 2020-05-06 at 14 56 41](https://user-images.githubusercontent.com/59567750/81180267-1142ee00-8fab-11ea-837e-91b32fb9f911.png)


In URDU the text is gone . Weird
![Screenshot 2020-05-06 at 14 58 35](https://user-images.githubusercontent.com/59567750/81180205-fb352d80-8faa-11ea-95c7-d995b3b4b21c.png)

**Comment by joe-getcouragenow** [comment]
Printing and Share should be put into a common Toolbar somewhere ?

**Comment by joe-getcouragenow** [comment]
https://pub.dev/packages/printing

works for web too !!

**Comment by winwisely104** [comment]
Direkt printing is not reliable with flutter yet.
https://github.com/flutter/flutter/issues/32249
Some languages have problems. Text colors are a problem. If there is a List, it will only prints a snapshot (like a screenshot) of the list, not multiple pages and so on ...


I think pdf creation is the only option for now.
The package mentioned above looks good. The extra line (pdf.js) in index.html is only for viewing the pdf with flutter web (we don't need that, only for printing).

BUT if we do this, it means we have to maintain a pdf layout besides the normal layout. This is huge. So It's may only interesting for pages with e.g. DataTable's or stuff like that.

**Comment by joe-getcouragenow** [comment]
Here is another approach where we accept we have to do PDF.


"Your Needs" is a list inside a list. Its a type of widget.
You will almost always end up with these higher level widgets in your App.
There is only a Ap bar title and a Icon also on that page.

So take the "List in a List" widgt and make a DART PDF for it also. BUT dont make it over the top. It can look sterile
Same for the Other standard widgets we use.
Our app is mostly this way in general
