### ISSUE TITLE
PACKAGES: Core, refactor DynamicWidgetService to be more like a manager

### ISSUE THREAD

**Issue by winwisely199** [getcouragenow/packages#419]
Current the service doesn't do too much all the work is mostly in the widgets. However, we will want to change that.

We want a "Manager" that can do the following

* Create and track each widget for us
* Generate the "build list" with the spacer widget in between each widget
* Control state for each "Form", this means that for each "Form" we would instantiate a new DynamicWidgetService (to DynamicWidgetManager)
* Return data from form

**The main challenge here is that in order to properly manage form state we have to "rerender" the form each time something changes, passing in the currently selected items each time.**

Example:

```
// in the xxxx_view_model.dart
DynamicFormManager formManager = new DynamicFormManager();

formManager.addDynamicDropdownButton(question, currentValue, callback);
formManager.addDynamicCheckbox(question, currentValue) ;
formManager.addField(TextFormField());
formManager.registerSave((data) {
    // Save with repos
}


// In the xxxx_view.dart
model.formManager.build()
````

**Comment by winwisely99** [comment]
Hive ?.
Why not use it's notification aspects ?

Seems obvious and no race conditions and boilerplate like if you writing a manager produ e all this technical debt

**Comment by winwisely99** [comment]
So data gets sent to client as proto.
Data gets cached I side hive.
So then when you go to. Page just check hive if it's there and if not go to server

This was explained to you a while ago.

Main project uses this technique.

Do t do anything on this.
Will get senior Dev to pick it up as it requires knowledge of these patterns and protobufs and unidirectional systems design.

Minio and NATS subscriptions needed first also

**Comment by winwisely199** [comment]
@winwisely99 it isn't so much that, all of those things make sense.

But each view model ends up having to track the form data individually, where as the manager could at least hold the form state in it. So view models just instantiate a new manager, and then use it in the view.dart to craft the form elements.

Less messy code in each model.

That's all.

**Comment by joe-getcouragenow** [comment]
OK i get it. SO will the hive cache help make the refactoring you want to do simpler is the key question ?
