### ISSUE TITLE
I18N Localization Standardization

### ISSUE THREAD

**Issue by winwisely199** [getcouragenow/packages#420]
The goal of this ticket is to put localization for each module locally inside of each module and generate language files with the make file.

Then, register it's delegate in main.dart of maintemplate so that as the language setting changes, each module responds automatically to using the correct set of language.

As a note the `Makefile` in maintemplate will probably need to call all the make commands in the submodules to make deployments and testing easier. one command will run them all.

[ ] Add i18n to mod-main
[ ] Create i18n delegate for mod-main
[ ] Register delegate with maintemplate
[ ] Setup makefile for modmain

**Comment by winwisely199** [comment]
**Completed:**

[X] Add i18n to mod-main
[X] Create i18n delegate for mod-main
[X] Register delegate with maintemplate
[X] Setup makefile for modmain

**Current Issues**
[ ] Mod main not responding to changes from main template, this is because of how the delegate system works
[ ] Mod main now breaks when built by itself, not sure what the fix is for that

**Comment by winwisely199** [comment]
**Issues Update**
[X] Mod main not responding to changes from main template, this is because of how the delegate system works **We had to cheat slightly, but so does every other package out there**
[X] Mod main now breaks when built by itself, not sure what the fix is for that
       **For this one it's a documentation/knowledge issue. We have to protect against a null every time and have a default english label to put you can see an example in the code**

**Comment by winwisely199** [comment]
Added delegate to example app so it can run locally with no issue

**Comment by winwisely99** [comment]
Couple on small tech debt things

- Lang and i18 folders are both there. Kill one of them.

- env.json settings file should be adjusted in CI. I think the sed is setting it to only EN now.
"locales": [
		"system",
		"en",
		"es",
		"fr",
		"ur"

- pubspec.yaml. the assets:
    - lang/de.json etc is redundant ?

Gen
- we will fix the CI soon to use the make file we use for everything and run the gen on everi. But not yet
