### ISSUE TITLE
PACKAGES: Flutter client upload files

### ISSUE THREAD

**Issue by Winwisly100** [getcouragenow/packages#430]
**Flutter Client**
- add flutter client to upload files.
- a file should be splitted in chunks.
- then each chunk is encoded to base64 then sended to server using stream grpc.

**Comment by winwisely99** [comment]
Must be using same approach as golang client. 
You have to decide if base64 or whatever is appropriate based on easy of use / perf.

And make it work with large videos. 100 mb video file must work.  Ben e why chunking.


Tests 
And must have a GUI test in flutter.
- dart test as part of the module 

And a CI test post deployment. 
-  calls same test
- must use grpc- web and grpc native

Makefile must show how to run these tests.
