### ISSUE TITLE
PACKAGES: i18n - new google way

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#445]
for reference: https://pascalw.me/blog/2020/03/09/localizing-your-app-with-flutters-new-gen-l10n-tool.html

and the code he is on about: https://github.com/flutter/flutter/tree/master/dev/tools/localization

We can wait until it hits us, OR try it out.

**Comment by winwisely199** [comment]
This may not work for sub-modules if it ultimately depends on the same initializeMessages that the current i18n stuff does.

I'll try to take a look when I"m up in the morning.
