### ISSUE TITLE
PACKAGE: Maintemplate, update make file to properly handle languages

### ISSUE THREAD

**Issue by winwisely199** [getcouragenow/packages#456]
1) Update makefile to put all lang files in the new standardized locations
2) Update makefile to generate .dart for maintemplate
3) Update makefile to generate all submodule languages

**Comment by winwisely199** [comment]
I started on https://github.com/getcouragenow/packages/issues/452 and then realized I needed to make some adjustments, so this is already half way done, will continue on it.

**Comment by joe-getcouragenow** [comment]
great thanks !!

**Comment by winwisely199** [comment]
Done
https://github.com/getcouragenow/packages/pull/459
