### ISSUE TITLE
CI: Local makefile for minikube

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#464]
so minikube is our priority for now. 
I think first thing it to add gofish installer to maintemplate make file
so then gofish can install all minikube and ctl for all OS's
use "dep-os" make target.

We will put all this into bootstrapper later once we have base working.

https://github.com/getcouragenow/k8/blob/master/bootstrap/makefile

use as a reference

**Comment by WinWisely268** [comment]
Bugs:

1. Install-prequisites is currently not working
2. The dependencies on gnu sed is preventing macos from running correctly 
3. The README is plain wrong and the order is not correct
4. docker registry is not correctly working in some machines without running ```eval $(minikube -p minikube docker-env)```
