### ISSUE TITLE
PACKAGES: mod-timespace

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#470]
Use this: https://pub.dev/packages/flutter_google_places

So in mod-main when asking use to pick their location we just make it visual and detect their location. SO much easier for us and them for now.

If we can get country and city and lat long out of the thing then we are good
Works on Web and Native so all good.

Can someone check this and let me know. 

Then we can do the fancy country picker and minio backend for the data later, as we are out of time for delibery.

**Comment by winwisely104** [comment]
https://pub.dev/packages/flutter_google_places is not possible due to cors issues

https://github.com/fluttercommunity/flutter_google_places/issues/93

**Comment by winwisely104** [comment]
- still to do:
1. The return result should be output to the screen if in debug mode.
Lat, long, all address data it gives.
2. Make it a name value list please.
3. clean up mod-main userinfo as right now it was only added to the current list

- endpoint 
It is actually still working, but my personal ip got blocked. Did not enforce time delay between the requests... So may still the way to go but enforcing the delay?

**Comment by winwisely104** [comment]
All done including request delay enforcement + a debug flag to show coordinates from selected location
