### ISSUE TITLE
PACKAGES: thin out maintemplate and mod-main

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#473]
Move into "sys-core"

Move everything we can to thing out maintemplate, and mod-main.

https://github.com/getcouragenow/packages/tree/master/mod-main/client/lib/core/package

https://github.com/getcouragenow/packages/blob/master/mod-main/client/lib/core/theme/app_theme.dart
- themes should be in maintemplate, so everything else gets them.

kill
- https://github.com/getcouragenow/packages/tree/master/maintemplate/client/lib/modules/writer

shared makefiles in packages root.
- i18n that is in mod-core.
- in i18n.mk, CURRENT_DIR = $(shell pwd) cant be used. Instead it must be TOLD what is the FileSystem Path.

---

**Comment by winwisely104** [comment]
- created sys-core. 

- Couldn't move easily https://github.com/getcouragenow/packages/tree/master/mod-main/client/lib/core/package. Master/Detail there is not correctly decoupled to move into sys-core. Another issue?!

- Maintemplate has still: Login, Startup, Settings. Need further instructions here, i guess they should be moved out also (if yes, where?)?!

- i18n.mk (now in sys-core) uses `pwd` for current_dir. The other scripts, as Maintemplate rely on it:

lang-gen-flu-submodules:## lang-gen-flu-submodules
	@(cd ../../mod-account/client && make lang-gen-flu)
	@(cd ../../mod-chat/client && make lang-gen-flu)
	@(cd ../../mod-main/client && make lang-gen-flu)

Maybe I am not seeing the point, as it is working
