### ISSUE TITLE
PACKAGES: LIftBridge due diligence

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#49]
1. Can a flutter web GRPC work with LiftBridge ?

2. LOE for Client as its not JUST grpc, but other stuff

**Comment by winwisely99** [comment]
1. Use flutter desktop
- faster
- can check grpc at least works

2. dont use docker
- just install via a make file

**Comment by Winwisly100** [comment]
1. generate protos
2. make mod-chat publish and subscribe to liftbridge
