### ISSUE TITLE
BOOTSTRAPPER & PACKAGES: make env and code gen EPIC

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#502]
We need env files for server, clients output locally and in CI using a make file.
RIght now its messy and hard to see what is going on.

Use these:
- https://github.com/getcouragenow/packages/tree/master/boilerplate
- https://github.com/getcouragenow/packages/blob/master/boilerplate/env.mk

Make an example to show it working.
- suggest doing it 

1. use protobuf as the source
- reflect to get the users github name ( e.g winwise xxx)
- Each dev uses protobufs to state the values they want
  - We just need a way to check that their protobuf conforms to the protobuf template and fail it at compile time !! 

2. use the protobuf template and go templates to gen the final files
- in our can the env file, that is NOT checked in.

3. We also use the traditional protobuf to gen the golang and dart classes that are designed to suck up the env settings at runtime.
- We just need an extra class to serialise the data from the env file up into it maybe. Not sure actually. Maybe we just gen the env to be JSON from the protobuf and so the golang and dart code naturally can deserialise it. Then we dont need mouls thing except for special cases.
- in the end this makes it easy to ensure that things work and if we change the protobug structure their confif loader also works.

4. So the protobuf uses composition like your own code Alex
- so in  mod, i use just me protobuf
- but main template protobuf uses the mods protobufs.

5. Lastly use the boilerplate files i make 
- this way we can get this going without breaking everyone, and when it works we can easily switch over.

6. CI needs to use the same make file
- we need to detect we are running on the github servers, so we know what protobuf to suck up
- We need to then just run the whole code gen just like a local dev would
- How to make it use a make file ?
  - https://github.com/getcouragenow/packages/issues/389

**Comment by winwisely99** [comment]
Alex are you taking this ?

**Comment by WinWisely268** [comment]
See my PR: https://github.com/getcouragenow/bootstrap/pull/62

**Comment by joe-getcouragenow** [comment]
Review
-------

Linting and checking maybe
- https://github.com/bufbuild/buf

casing
- leave for now.

make test-json
- need protoreflect import.

**Comment by joe-getcouragenow** [comment]
1. Dart
- How to gen a Dart config from the protobuf ?
  - use the gotemplate technique and outputs same structrue as we currently do for go.

2. Make the BS installable 
- Keep the CI folder and make a new SDK folder which will have a normal CLI using cobra
- so move the protofig stuff to SDK folder ( 4 binaries), and the make 
- makefile for protofig ( See boilerplate/config/README)
- so must covert mage to a CLI: https://github.com/getcouragenow/bootstrap/issues/69
- so must put the makefile for config into the boilerplate
- so must fo embedding of boilerplate: https://github.com/getcouragenow/bootstrap/issues/67
- move i18n into the ci CLI
- move all examples into examples folder

2. Use in packages env.json can now use the protobufs
- update the flutter code to use it

**Comment by WinWisely268** [comment]
Just tested in clean virtual machines, so we actually need 5 binaries

the extra binary is ````google.golang.org/protobuf/cmd/protoc-gen-go```
