### ISSUE TITLE
PACKAGES: Kanban board

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#512]
Its here: https://github.com/getcouragenow/packages/tree/master/mod-kanban

It uses a widget called trello board.
It needs slight adjustment to work.

We need mock data for now.
Then will adjust the gsheets for loaded data.

Intent of the Kan Ban is needed to even make the mock data, let alone the backend.

Explained here: https://docs.google.com/document/d/1wlcnvPFvEj88tkbeiX-zQKTZFzB6DN6FjNkubeSIXPM/edit#heading=h.r4qufvg6axj4

- Linked via TAGS/Labels to Supply/Demand aspects from Layer 1

- Linked via Task Management (Layer 2) back to Enrolment (Layer 1) via the TAGS
- It is like a CMS basically because when you do an Issue in KanBan you're creating Chats, Video Conf, Docs, etc links in those issues. 

----

Its exactly like how github projects works.
like here: https://github.com/orgs/getcouragenow/projects/1

# Architecture

Router: We use this: https://github.com/Flutterando/modular
- its makes all our modules look the same.
- less boiler plate.

Data. We us Hive to store data client side.
https://pub.dev/packages/hive
- its code generates the "boxxes".

Backend is grpc and NATS.
Once in CI k8 / envoy allows grpc to work for flutter web also 

---

# Architecture
- Introduce Hive now (use repository)
  - Example: https://github.com/getcouragenow/main
  - 1. At start: load the assets (backend) into HIVE (frontend kv db)
  - 2. At READ operation, IF offline, read from HIVE.
  - 3. At CUD (mutations) operations are events and so IF offline, send to HIVE.
  - 4. Whenever a change on HIVE happens, the GUI pages get told.

- Syscore
  - online / offline generic code
  - org code: model, repository, hive code.

# Functionality

Main Screen
Use Trello as a base from mod-cal. see makefile
- a Card is the same as a github issue. We just call them cards ( like KanBan cards).
- has columns
- can move "card" from one column to another
- can re-order "card" within a column
- make sure you fork Trello btw.
- its mostly works now but reordering does not.

Tags ( which comes from Layer 1)
- we use tags rom Layer 1 as a higher order mapping to Cards.
- so a card is always mapped to an org tag.
- a card can have many tags. OUT OF SCOPE.
- need to create a screen to add and remove org tags * Because we dont have security model yet. tag CRUD editor ( CRUD = Create, Read, Update, Delete)

Search
- by tags, will only show cards that match the tags

Card edit / delete
- clicking a card allows you to edit it.
- you can delete a card from the edit screen.
- the editor for a card is a simple Text Editor
- you can also create other module links that are associated back to a Card. 
  - 2 options ( use option 1)
      - 1  these are shown to the side of a card as link and when clicked take you to that Module.
      - 2 user just clicks the module on the rail.
- mods that can be linked are;
   - cal: The idea is that the issue now has a due date.
   - doc: see mod-write 
   - ion. See mod-ion. Its video conferencing
   - chat: see mod.chat: its a chat session

## Code

Use this as a basis ?

https://www.youtube.com/watch?v=kRIuxf92iFY

https://github.com/PonnamKarthik/FlutterTrelloCards

What the protobuf will look like we dont knwo yet.

But getting it running in the demo with mock would be useful

**Comment by winwisely99** [comment]
This needs more design though.

Don't take yet

**Comment by winwisely104** [comment]
Mod-kanban init is done

Following things are missing to get the first basic version working:

1. Use the Reorderablelistview from the flutter sdk itself. So we can scroll vertically and drag and drop items (with a long press). 

2. Add item button (currently there is no way to add an item)

3. Fix the theming for dark mode (some texts are colored white on white background)
