### ISSUE TITLE
PACKAGES: i18n - get maintemplate using the reusable make files

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#521]
We are getting lots of errors with missing translations.

![Screenshot_20200502-002918](https://user-images.githubusercontent.com/56028033/80846306-0d5e4700-8c0c-11ea-97bc-59d294bfb076.png)

![Screenshot_20200502-002904](https://user-images.githubusercontent.com/56028033/80846327-194a0900-8c0c-11ea-8b8d-3d61de670d1e.png)

The above should be impossible to screw up. But it did 😔

Also we need to stop including the JSON. It's not needed I think as the ARB is all that needed for the release. The app is up to 9 mb ! 

I also think we need to save settings using shared preferences or hive. The app is so big that android is reloading the app when it goes out of foreground and back into foreground and sonlooses whatever language you selected . This is why I wanted setting to be protobuf based because then the a new version with changed setting won't blow up when it reads the stored settings JSON.

Either the developer missed a text field leaving it as English or the modules translation is not being updates 

Let's start to use the boilerplate makefile system that is now setup

Also let's change CI to force translation all the way down.
The root makefile is in the root of maintemplate.

The lsng.mk in boilerplate will need some adjustment I expect

The i18.km is sys-core can be deleted ?

**Comment by winwisely104** [comment]
I was looking into the intl stuff, but i am afraid i can't do anything as long as the go script is not working correctly. It fails with mod-main:

Stacktrace:
```
~/projects/getcouragenow/packages/mod-main/client on master*
$ make lang-gen-flu
fatal: No names found, cannot describe anything.
panic: runtime error: index out of range [35] with length 35

goroutine 1 [running]:
github.com/getcouragenow/bootstrap/tool/i18n/services.getTranslatedMaps(0x163dd06, 0x2, 0xc000294700, 0x6, 0x8, 0xc00018b200, 0x1, 0xc0001c9e00, 0x6, 0x6)
	/Users/alec/workspace/go/pkg/mod/github.com/getcouragenow/bootstrap/tool/i18n@v0.0.0-20200430105819-54dc86e15368/services/translation.go:66 +0x5c9
github.com/getcouragenow/bootstrap/tool/i18n/services.GenerateMultiLanguageFilesFromTemplate(0x7ffeefbff4bf, 0x52, 0x7ffeefbff473, 0x40, 0x7ffeefbff51b, 0x4, 0x163e479, 0x4, 0x163dd06, 0x2, ...)
	/Users/alec/workspace/go/pkg/mod/github.com/getcouragenow/bootstrap/tool/i18n@v0.0.0-20200430105819-54dc86e15368/services/write.go:298 +0x1b3
github.com/getcouragenow/bootstrap/tool/i18n/cmd.glob..func1(0x1b02d20, 0xc000114510, 0x0, 0x9, 0x0, 0x0)
	/Users/alec/workspace/go/pkg/mod/github.com/getcouragenow/bootstrap/tool/i18n@v0.0.0-20200430105819-54dc86e15368/cmd/flutter.go:28 +0x1bd
github.com/spf13/cobra.(*Command).execute(0x1b02d20, 0xc000114480, 0x9, 0x9, 0x1b02d20, 0xc000114480)
	/Users/alec/workspace/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x1b03260, 0x1042dca, 0x1abfe40, 0xc000000180)
	/Users/alec/workspace/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/alec/workspace/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/getcouragenow/bootstrap/tool/i18n/cmd.Execute()
	/Users/alec/workspace/go/pkg/mod/github.com/getcouragenow/bootstrap/tool/i18n@v0.0.0-20200430105819-54dc86e15368/cmd/root.go:29 +0x31
main.main()
	/Users/alec/workspace/go/pkg/mod/github.com/getcouragenow/bootstrap/tool/i18n@v0.0.0-20200430105819-54dc86e15368/main.go:6 +0x20
make: *** [lang-gen-flu] Error 2
```

I think you mentioned several separated issues here:

> I also think we need to save sertings using shared preferences or hive. The app is so big that android is reloading the app when it goes out of foreground and back into foreground and sonlooses whatever language you selected . This is why I wanted setting to be protobuf based because then the a new version with changed setting won't blow up when it reads the stored settings JSON.

IMHO-> should be a new issue

> Let's start to use the boilerplate makefile system that is now setup
Also let's change CI to force translation all the way down.
The root makefile is in the root of maintemplate.
The lsng.mk in boilerplate will need some adjustment I expect
The i18.km is sys-core can be deleted ?

-> i can say if the go tool is fixed

> Either the developer missed a text field leaving it as English or the modules translation is not being updates

-> translations are there but, same as above, waiting for the go tool fix.

> Also we need to stop including the JSON. It's not needed I think as the ARB is all that needed for the release. 

-> think the same, but need to verify when things are running

> The app is up to 9 mb !

-> new issue, we can shrink some images e.g.

**Comment by joe-getcouragenow** [comment]
@winwisely99  Please fix the go code :)

**Comment by joe-getcouragenow** [comment]
First fix it here: https://github.com/getcouragenow/bootstrap/issues/70

**Comment by winwisely104** [comment]
both screenshots above should be fixed now with https://github.com/getcouragenow/packages/pull/556
