### ISSUE TITLE
PACKAGES: Perf Issue with flutter - general cleanup

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#532]
Perf:
12 sec load time sentry from fresh

- LANG needs JSON ? yes or no. (win104)
- lazy loading of JSON from Server when they first boot, and only load their lang json

Can we do lazy loading of Modules (actual compiled decode) using Flutter Modular.
- PWS can do this, why cant we !
- ask flutter modular guys (win99)

Dashboard on resize rate sucks:
- perf is shit because its constant re-render.
  - 1. dashboard is reloaded data everytime ? (win104)
 - check dashboard and other. All pretty bad

Dashboard on Rails (full relayout) resize in OK.
- perf is ok because its ONE re-render. (win104)

Profiling:
- See the 80/20 area - Looking for the SPOP bottleneck

**Comment by winwisely104** [comment]
verify if flutter modular is doing lazy loading (dependency injection)

**Comment by WinWisely105** [comment]
https://pub.dev/packages/flutter_modular#dependency-injection
https://pub.dev/packages/flutter_modular#lazy-loading

Can use dependency-injection to lazy-load data.

Not sure if flutter_modular already does this

**Comment by WinWisely105** [comment]
Just scanned through code for flutter_modular

Looks like it only lazy-loads dependency injections. Everything else is loaded at runtime.

**Comment by winwisely104** [comment]
First step: 

- Removed unnecessary assets + shrinked sizes of images.
- Mock data is static now
- Better key handling in nav_rail

we could activate the skia web assembly option (which still is experimental, but i've heard a lot of people are using it)

`flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true` 

Laggy scrolling large content with flutter web is a known issue and should be improved by now on channel master:

https://github.com/flutter/flutter/issues/42987

**Comment by winwisely104** [comment]
Tested with `--dart-define=FLUTTER_WEB_USE_SKIA=true`. Application size was not going up, but mod-write with zefyr was not working as expected, so not an option for now.
