### ISSUE TITLE
fix mod-chat

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/packages#590]
The update to flutter modular means a few things have busted. Get it back working.
https://github.com/getcouragenow/packages/tree/master/mod-chat/client

Server is broken so dont worry about it.
https://github.com/getcouragenow/packages/tree/master/mod-chat/client

We will then upgrade all the packages
- start at modules making sure examples run
- then finish with main template.
at that point CI shoudl work and autodeploy to good cloud at: https://maintemplate.ci.getcouragenow.org/

**Comment by cloudwebrtc** [comment]
There are two errors when using the latest version of flutter beta channel.

fixed https://github.com/getcouragenow/packages/pull/594

**Comment by joe-getcouragenow** [comment]
CI is yelling about Router: https://github.com/getcouragenow/packages/runs/1108254949?check_suite_focus=true
Pretty easy change to all modules that maintemplate loads.

Can you do this ?

**Comment by cloudwebrtc** [comment]
Ok, let me fix it.

**Comment by joe-getcouragenow** [comment]
I think we can close this ?

**Comment by cloudwebrtc** [comment]
Yes, I think so, testing locally is fine.

**Comment by joe-getcouragenow** [comment]
thanks. closing
