### ISSUE TITLE
PACKAGES: grpc-web without envoy.

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#95]
https://medium.com/safetycultureengineering/proxy-grpc-web-directly-in-your-go-server-without-envoy-7fbec326cb21

Worth a try and easy. @winwisely112 

Great for Devs 
No need for minikube etc.

Because we are using pure golang backend nothing else needed

**Comment by winwisely112** [comment]
https://github.com/improbable-eng/grpc-web/tree/master/go
I have added it to main template server but have not tested yet. we can test it with mod-chat. another idea is to have a mod-test for these purposes. to test main template server features without dependency to other mods.   
we can add a cli flag like --local to activate it for local developments.
